### ISSUE TITLE
Provide stand-alone operation

### ISSUE THREAD

**Issue by arnetheduck** [nimterop/nimterop#125]
Use case is to generate wrapper once and use the generated file instead of running nimterop on every compile / requiring end user of library to have nimterop. This keeps the dependency tree of projects using wrappers a lot more manageable (no rust etc needed).

See https://github.com/arnetheduck/nim-sqlite3-abi/blob/master/update.sh#L23 for an example of this kind of setup - here are some things that would help:

* [x] avoid relying on code reordering / experimental features (wrappers are typically dumb anyway and this helps supporting older nims)
* [x] avoid importing `nimterop/types`, expanding whatever's in there into the wrapper
* [x] avoid absolute paths
* [x] possibly: avoid generating header directives completely

**Comment by genotrance** [comment]
Code reordering is not really needed and has been removed from the `pragma` branch. Nimterop already reorders things in a logical way. Once pragma is merged, this will be done.

You could always still rely on nimterop/types without having to regenerate wrappers every time by copying the file over. It is only expected to get larger as more C/C++ interop code gets added into it, reducing the need for a Nim API over every wrapper. Open to ideas though.

There's no getting away from absolute paths since many os procs aren't available at compile time. For example `relativePath()`. Absolute paths are needed especially when parsing the preprocessor outputs and few other places. No good answer on that yet.

Headers, already discussed in IRC, unclear if we can get rid of it.

**Comment by genotrance** [comment]
Headers are no longer included unless explicitly requested using the `-H` flag with toast. Without headers, there are no absolute paths in the rendered wrappers either.

Only open item is importing nimterop/types. While we haven't done much in terms of adding more C/C++ interop that makes life easier, that's still on the table. Still open to discussion on that item. 

Any other suggestions that make standalone operation better are welcome.

**Comment by arnetheduck** [comment]
`sqlite` is an example that doesn't need `types`, so a first step is to import it only when something from there is needed.

also, as long as none of the stuff in `types` gets reexported, there also shouldn't be any harm in simply including its text in each generated file, again on a need basis.

there is one more point that would make stand-alone more slightly more convenient: the option to write the output to a file - redirecting stdout has the adverse effect of also writing random junk that nim itself prints during compilation - `CC`, warnings etc - of course, with the right magic incantation these can be shut off, but it's a bit annoying.

**Comment by genotrance** [comment]
This will be fixed in v0.6.1.

**Comment by genotrance** [comment]
Note #239 is also fixed so generated wrappers are even more independent going forward.
