### ISSUE TITLE
[Feature] Option to dump debug in a file

### ISSUE THREAD

**Issue by mratsim** [nimterop/nimterop#127]
I'm currently working on a codebase (https://repo.or.cz/w/isl.git) with procs in [60 header files](https://repo.or.cz/isl.git/tree/HEAD:/include/isl) but most of them irrelevant for general purpose (intended audience are polyhedral compiler developers).

I'd like to be able to dump the generated procs to a file to check if what I need is actually included and what I don't is not.

FYI, here is the current state of my wrapper: https://github.com/mratsim/nim-isl/tree/44b05f08fe21b37038f57d8643314a728bbf41d5

**Comment by genotrance** [comment]
I'm not certain if I already asked this in IRC, but how is this different from setting `cDebug()` and then redirecting to a file on the shell? Is there a use case for this to be set always, not just part of checking the output?

**Comment by mratsim** [comment]
The shell redirection only allows to distinguish between stdout and stderr so nimterop output will be mixed with compiler outputs and potentially CI/CD outputs in a continuous integration/delivery setup.

**Comment by genotrance** [comment]
This is not as trivial - the generated file should include almost everything in the original wrapper.nim with the cimport calls replaced with the actual generated code. They could be surrounded with code that isn't easy to figure out. E.g. [archive.nim](https://github.com/genotrance/nimarchive/blob/master/nimarchive/archive.nim#L113).

Ideally there's a way to echo a repr of the AST at a given point which represents the state of the AST after all the CT work.

**Comment by genotrance** [comment]
I've implemented file output for toast with the -o flag. Doesn't help cImport yet but trying to make toast more useful by itself.

**Comment by genotrance** [comment]
Nimterop is getting better at generating standalone wrappers:
- `cOverride()` already gets embedded into the generated wrapper, better to use that than bare types and consts which do not get propagated into the wrapper.
- `types.nim` is no longer imported so generated wrappers can run without any nimterop dependencies.
- The `dynlib` param to `cImport()` and `toast` can also simply point to the shared library instead of having to be a variable containing the path - it will be injected in the wrapper as is, no longer depending on the caller.
- The toast content is no longer injected by `cImport()` but included from a file.

With these changes, it is now getting more possible to create final wrappers that contain everything. All that remains is to add a param to `cImport()` specifying where to write the final wrapper. This way, the end user can either import the nimterop wrapper file or the generated wrapper into the main application.

**Comment by genotrance** [comment]
This will be fixed in v0.6.1. `cImport()` now accepts a `nimFile` param which can be used to write the generated wrapper to a known location.

**Comment by genotrance** [comment]
Note #239 is also fixed so generated wrappers are even more independent going forward.
