### ISSUE TITLE
Feature: cOverride and object's dependency tree

### ISSUE THREAD

**Issue by mikra01** [nimterop/nimterop#133]
Hi, I recently wrapped odpi-c. It was very straightforward with nimterop :-) - thanks for that great tool. unfortunately some structs are not processed by treesitter and silently discarded. no clue why. so I came up and put these objects manually into cOverride.  

**Problem**: if you have only native dependencies everything is fine unless it contains some child dependencies (which are successfully parsed by treesitter) but cOverride bailed out with "unknown type". At the end I found me processing the entire dependency tree manually :-(.

I don't know if it's possible but it would be nice if cOverride has knowledge about the already parsed child-dependencies.

**Comment by genotrance** [comment]
Thanks for using nimterop and reporting this issue. Currently, `cOverride` is just a blob at the beginning which is I've found useless for more complex wrappers since missed symbols will most likely refer to code that will be processed by `cImport` later. Ideally, `cOverride` should override in place rather than at the top. That way, only symbols which weren't recognized would need to be overridden.

Problem is that for this to happen, nimterop needs to recognize syntax that it doesn't recognize! If it could recognize it, it could wrap it already. I have some ideas for this though:
- Have a catchall pattern to find symbol names and inject code - I'm not sure if such patterns will really catch every scenario or the performance implications - needs more thought, but ideal solution if done right
- Have a `cPlugin` hook to inject onSymbol but would be more tedious for multiple instances

Any other ideas welcome.

**Comment by genotrance** [comment]
The override branch attempts to fix this issue. Appreciate your feedback.

https://github.com/nimterop/nimterop/tree/override

**Comment by genotrance** [comment]
Fixed in https://github.com/nimterop/nimterop/commit/3ae716fff6e4b79257a6727eca794850a84f19b8.

**Comment by mikra01** [comment]
sorry for my very late response. everything is working fine now.
