### ISSUE TITLE
toast results aren't cached with `nim check`

### ISSUE THREAD

**Issue by liquid600pgm** [nimterop/nimterop#144]
This makes `nim check` very sluggish and annoying to use, and hurts developer performance when an IDE uses `nim check` for error checking.

Possible solution: use own method of caching when `defined(nimcheck)` is true.

**Comment by genotrance** [comment]
Okay, I vaguely remember @Araq turning off some behavior in `nim check` to avoid weird side-effects but couldn't find any commit, issue or PR related to it. It is in effect 1.0+ but isn't in <= 0.20.2.

Turns out `gorgeEx()` still works but `writeFile()` does not so it is not possible to write plugin files when `nim check` is run. 

Looks like nimterop shouldn't do anything if `nim check` mode. Wonder if there's a simple way to globally do nothing rather than having to check in every exported user facing proc.

**Comment by genotrance** [comment]
I have created a [branch](https://github.com/nimterop/nimterop/tree/issue144) with a potential fix for this issue. Considering the new security setup where gorge/writeFile don't work in nimcheck/nimsuggest, user is now expected to run `nim c` at least once. It will create the required cache which can then be leveraged in these modes.

I can verify that it works correctly in nimcheck mode but I don't see nimsuggest working in neovim, the symbols are still unknown. I'm not sure how to debug so any tips appreciated.

cc @disruptek @alaviss

**Comment by genotrance** [comment]
Figured it out - nimsuggest was setting getCurrentCompilerExe() to nimsuggest which broke the caching. Testing in the issue144 branch. Once it passes CI, will merge.
