### ISSUE TITLE
[Bug] Character constant '_' is not allowed

### ISSUE THREAD

**Issue by jyapayne** [nimterop/nimterop#178]
In the `checkIdentifier` proc, there is this line:

```nim
doAssert name[0] != '_' and name[^1] != '_', errmsg & " leading/trailing underscores '_'"
```

The problem is that if there is a constant in the C code that is just an underscore (ie `'_'`), this assert will fire.

**Comment by genotrance** [comment]
I thought about this for a while and I cannot think of any case where you'd run into an identifier that is more than one `_`. This is the enum logic and the only case where you'd run into `_` is this one that you've found since the value of the enum has to be int or char. Other variations could be `'_' >> 2` or similar but still just a single `_`.

Making a simple change for now, we'll have to see if it is good enough.
