### ISSUE TITLE
ABI break due to the lack of .importc in struct definitions

### ISSUE THREAD

**Issue by liquid600pgm** [nimterop/nimterop#202]
I've been recently struggling with a strange segmentation fault that was occuring in rapid/audio for seemingly no reason. After a little bit of debugging, I found out that the order of fields in Nim-bound structs vs C structs differs. Here's proof using GDB:
```
(gdb) n
126	  outstream.sample_rate = ROutputSampleRate
(gdb) p outstream
$5 = (tyObject_SoundIoOutStream__OKkCgy1bVSkwLimlF5TtWw *) 0x5555555e1ee0
(gdb) p *outstream
$6 = {device = 0x7fffec00cc50, format = 3, sample_rate = 0, layout = {name = 0x0, channel_count = 0, channels = {0 <repeats 15 times>, 93824992255547,
      93824992257383, 0, 0, 0, 0, 0, 0, 0}}, software_latency = 0, volume = 0, userdata = 0x0, write_callback = 0x0, underflow_callback = 0x0,
  error_callback = 0x0, name = 0x0, non_terminal_hint = 0 '\000', bytes_per_frame = 0, bytes_per_sample = 0, layout_error = 0}
(gdb) p (struct SoundIoOutStream)*outstream
$7 = {device = 0x7fffec00cc50, format = SoundIoFormatS16LE, sample_rate = 0, layout = {name = 0x0, channel_count = 0, channels = {
      SoundIoChannelIdInvalid <repeats 24 times>}}, software_latency = 0, volume = 0, userdata = 0x0, write_callback = 0x0,
  underflow_callback = 0x555555559e3b <default_underflow_callback>, error_callback = 0x55555555a567 <default_outstream_error_callback>, name = 0x0,
  non_terminal_hint = false, bytes_per_frame = 0, bytes_per_sample = 0, layout_error = 0}
(gdb) n
127	  outstream.software_latency = latency
(gdb) p (struct SoundIoOutStream)*outstream
$8 = {device = 0x7fffec00cc50, format = SoundIoFormatS16LE, sample_rate = 0, layout = {name = 0xbb80 <error: Cannot access memory at address 0xbb80>,
    channel_count = 0, channels = {SoundIoChannelIdInvalid <repeats 24 times>}}, software_latency = 0, volume = 0, userdata = 0x0,
  write_callback = 0x0, underflow_callback = 0x555555559e3b <default_underflow_callback>,
  error_callback = 0x55555555a567 <default_outstream_error_callback>, name = 0x0, non_terminal_hint = false, bytes_per_frame = 0,
  bytes_per_sample = 0, layout_error = 0}
```
As can be seen in the above debugger output, setting `sample_rate` from Nim actually sets `layout.name` in C!
My guess is that this is due to the lack of `{.importc.}` pragmas on the bound structs (I checked this using `cDebug()`). This probably causes problems because the Nim compiler's free to reorder fields as much as it wants (which it probably doesn't do, but GCC may do that). In the end, this causes an ABI break, and a segfault when trying to use soundio.

Here's the wrapper: https://github.com/liquid600pgm/rapid/blob/master/src/rapid/lib/soundio.nim
It used to work on older versions of Nimterop, it was likely broken by the AST2 refactoring, but I'm not entirely sure about that.

**Comment by genotrance** [comment]
Thanks for the report. This was implemented as part of https://github.com/nimterop/nimterop/issues/169 which was requested by @arnetheduck.

I've documented it in the [change log](https://github.com/nimterop/nimterop/blob/master/CHANGES.md) under breaking changes.

What I'm on the fence on is whether this should be a breaking change or whether we should revert back to the legacy behavior and make the `-H` flag turn of the header and importc (opt out) instead of making it opt in.

Considering this leads to crashes that are hard to debug, I feel we should switch. However, I'm unsure if this is actually a bug in the type generated or a reordering issue. 

Cc: @Araq @leorize @kaushalmodi

**Comment by genotrance** [comment]
Worked with @liquid600pgm on this issue and it turned out that enum size was incorrectly `distinct int` instead of `distinct cint` and was causing the field misalignment. This has already been fixed so all that was required was to pull latest #head.

The question still remains though - seems like having users explicitly opting out of `{.header.}` and `{.importc.}` will be safer for inexperienced users and simultaneously makes it a non-breaking change. But it might obscure real issues with the wrapper generation code.

**Proposal is to switch `-H` from opt in into opt out. Open to feedback.**

Debug details:

```nim
type
  SoundIoOutStream* {.bycopy.} = object
    device*: ptr SoundIoDevice
    format*: SoundIoFormat            # Enum which was `distinct int` instead of `distinct cint`
    sample_rate*: cint
    layout*: SoundIoChannelLayout
    software_latency*: cdouble
    volume*: cfloat
    userdata*: pointer
    write_callback*: proc(a1: ptr SoundIoOutStream, frame_count_min: cint, frame_count_max: cint) {.cdecl.}
    underflow_callback*: proc(a1: ptr SoundIoOutStream) {.cdecl.}
    error_callback*: proc(a1: ptr SoundIoOutStream, err: cint) {.cdecl.}
    name*: cstring
    non_terminal_hint*: SoundioBool
    bytes_per_frame*: cint
    bytes_per_sample*: cint
    layout_error*: cint
```

**Comment by timotheecour** [comment]
possibly relevant flags/procs:
* NIM_STATIC_ASSERT
* -d:checkAbi

possibly relevant issues:
* https://github.com/nim-lang/RFCs/issues/205
* https://github.com/nim-lang/Nim/issues/13927 https://github.com/nim-lang/Nim/issues/13927
* https://github.com/nim-lang/Nim/issues/13945 CT sizeof(T) is wrong if T or any member is empty object

**Comment by genotrance** [comment]
I presume `-d:checkAbi` is only relevant when you have `{.header.}` and `{.importc.}` so it won't really help users with debugging if `includeHeader` is opt in and they run into an ABI issue.

**Comment by timotheecour** [comment]
oh, very weird that you're allowing mapping without importc

**Comment by genotrance** [comment]
Skipping `{.importc.}` is mainly available to enable generation of wrappers that can be used standalone without the headers. All the user has to provide is the binary at runtime.

I believe there's only one case where you need the header at compile time - headers contain `static inline` functions that user wants - no way to reference these unless you include the headers. Considering nimterop generates wrappers directly from headers, I believe all fields and sizes should be visible to it. It will be great to know if there are any other cases.

I'm still on the fence whether anything has to change with `-H` behavior. If users face an issue, they can turn on `-H` and `-d:checkAbi` and verify if nimterop is doing anything wrong. If they want `static inline`, they can use `-H`. The question is what's a good default for the community.

**Comment by timotheecour** [comment]
here's my proposal:
* keep -H as opt-in; https://github.com/nimterop/nimterop/issues/169 was a super nice improvement that gives isolation, generating pure nim code with no dependency on C header files
* change nimterop wrapper generation to include auto-generated ABI checks at the end enabled with `-d:nimteropCheckAbi`
```nim
# auto-generated nim wrapper
type Foo1 = object ...
...
# end of declarations
when defined nimteropCheckAbi:
  {.emit:"""
#include "header1.h"
#include "header2.h" # etc; all headers that are parsed by nimterop during this build
...
void nimteropCheckAbis(){
  NIM_STATIC_ASSERT(sizeof(`Foo1`) == sizeof(Foo1), "nice err msg pointing to all relevant context, eg where Foo1 is declared in the wrapper, etc ");
  // in future work, add additional abi checks for alignof, and offsetof for each field
}
".}
  proc nimteropCheckAbis*() {.importc.}
  when isMainModule: nimteropCheckAbis()
```
* when user passes a flag `--nimteropCheckAbi` in nimterop command (maybe on by default), nimterop runs `nim r -d:nimteropCheckAbi mygeneratedwrapper.nim` right after the file is generated

that's very flexible and gives you the best of both worlds:
* it generates pure nim code with no dependency on C headers
* it runs (by default) ABI checks immediately after a wrapper is generated
* it allows a wrapper user to re-run the abi checks long after the wrapper was generated (eg after running `brew install mylib` to make sure ABI checks still pass after some C libraries were updated)
* it allows arbitrary sanity checks on the wrapper, beyond the ones I've added via `-d:checkAbi`; in particular you can also run ABI checks on generated procs:
```
// for non-void-return procs:
NIM_STATIC_ASSERT(sizeof(`fun1`()) == fun1())
```
as well as other sanity checks (not limited to ABI checking) that a user could specify in the wrapper (eg the "test" section inside most brew formulas)

**Comment by genotrance** [comment]
Thanks for all the feedback. Here are my current thoughts based on the inputs received so far.

> generating pure nim code with no dependency on C header files

Nimterop relies on the preprocessor's output, making the wrapper OS/compiler/package specific. I've explained more in the README but presence of the header file is kind of unavoidable. It is definitely viable for simpler libs that do not require extensive platform detection which justified implementing a mode that excluded the header pragma. It does not make sense to make it the default though.

> include auto-generated ABI checks

Given header presence is required for ABI checks, users can simply set `-d:checkAbi` and it just works. I just enabled this for all nimterop tests and will do so for all the wrappers I create. I don't know if nimterop really needs to add more around this.

Maybe once Nim enables `{.define: "checkAbi".}`, we can set it by default for wrappers that `includeHeader` so that checks are always done, unless it is too slow.

Here's the current matrix of possibilities which I am planning to support:

**useHeader: includeHeader = true, dynlib = false**
- Types = `{.header, .importc.}`
- Static inline = `{.header, .importc.}`
- Procs = `{.header, .importc.}`
- Lib = `{.compile.}` or `{.passL.}`

**useHeaderDynlib: includeHeader = true, dynlib = true**
- Types = `{.header, .importc.}`
- Static inline = `{.header, .importc.}`
- Procs = `{.dynlib, importc.}`
- Libs = loaded by dynlib

**noHeader: includeHeader = false, dynlib = false**
- Types = `{.bycopy.}`
- Static inline = not available
- Procs = `{.importc.}`
- Lib = `{.compile.}` or `{.passL.}`

**noHeaderDynlib: includeHeader = false, dynlib = true**
- Types = `{.bycopy.}`
- Static inline = not available
- Procs = `{.dynlib, importc.}`
- Libs = loaded by dynlib

**Comment by timotheecour** [comment]
> presence of the header file is kind of unavoidable.
> Nimterop relies on the preprocessor's output

my point is that it's needed only when generating the wrapper, after that it's not needed. A wrapper could be generated in some machine and used in other machines.

I'd like nimeterop generated wrapper to be pure nim so it doesn't require C headers lying around. The only external dependency becomes shared or static libraries.
benefits:
* no need to maintain potentially complex set of compiler flags (includes, define symbols, etc) that were only needed during the build process
* you can distribute those nimterop wrappers to other users (or other VM's you own) with compatible platform, all they need is shared/static libraries (and these could be bundled in distributions too depending on situations)

> making the wrapper OS/compiler/package specific

yes but doesn't mean end user has to do that. The wrapper generation can be automated in separate VM's and distributed to end users. And cross compiling (eg via zig, see https://github.com/nimterop/nimterop/issues/205) means you could generate wrappers for different OS/cpus from a single machine (eg during CI/release process).

> Given header presence is required for ABI checks, users can simply set -d:checkAbi and it just works

that won't work for generation of pure nim wrappers (without header dependency for users of the wrapper).

**Comment by genotrance** [comment]
I understand that this is the ultimate and ideal goal and nimterop could potentially enable it by generating and consolidating multiple wrappers across combinations. However, it currently requires the wrapper author to do all that work and does not have any built-in functionality or recommended workflows.

The way nimterop works today doesn't justify changing the default. Maybe in the future this is all simpler and nimterop can be relegated to running in a build matrix somewhere and end users only install static wrappers. We aren't there today.

Lastly, I intend focusing on C++ wrapping once 0.5.x becomes stable rather than refining static wrapper generation. This is because you still get functional wrappers today and motivated users can fill the gaps but there's nothing nimterop can do today for C++ libs. Maybe with more contributions, things will evolve faster.

**Comment by genotrance** [comment]
This has been implemented in the pragmas branch and will be merged once tests pass. A section has been added to the [README](https://github.com/nimterop/nimterop/blob/pragmas/README.md#header-vs-dynlib) to explain it further, feedback appreciated.

Any wrapper authors who used `--includeHeader | -H` will eventually have to remove it since it now means the opposite. I have already cc'd those who tried out `-f:ast2` so hopefully the impact is minimal.

**Comment by timotheecour** [comment]
> Any wrapper authors who used --includeHeader | -H will eventually have to remove it since it now means the opposite

that sentence was ambiguous; docs https://github.com/nimterop/nimterop/blob/pragmas/README.md#header-vs-dynlib mention `--noHeader` so I'm guessing `--includeHeader` doesnt' exist anymore?
Also, double negations are not ideal, why not use `--headers:on|off` ?

**Comment by genotrance** [comment]
> so I'm guessing --includeHeader doesnt' exist anymore?

Yes, headers are always included unless `--noHeader`. You need headers for `static inline` procs or to `-d:checkAbi`. If absolutely sure, user can use `--noHeader` and that section attempts to explain all these things.
